name: Master - Build, Test & Pack

on:
  push:
    branches: [ main ]

jobs:
  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.1.1
      with:
          path: './SysMonitor.UI'
          
    - name: Configure Version
      uses: microsoft/variable-substitution@v1
      with:
        files: './SysMonitor.UI/package.json'
      env:
        version: ${{ steps.extract_version.outputs.version }}-CI-${{ env.RUN_NUMBER }}

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install modules and Build for Production
      run: |
        npm i
        npm run build

    - name: Run Tests
      run: npm run test

    - name: Package Electron App
      run: npm run electron-package

  build-service:
    name: Build Service
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Clean
      run: dotnet clean ./SysMonitor.Service/SysMonitor.Service.sln -- configuration Release && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore --disable-parallel
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  package-installer:
    name: Package Installer
    steps:
    - name: Package Installer
      uses: team-mst/mst-inno-setup-wrapper@v1
      with:
        script-name: ./SysMonitor.Service/SysMonitor.Service/SysMonitor.Setup.iss
        working-directory: ./
        installer-file-name: SysMonitor.Setup.${{ steps.extract_version.outputs.version }}-CI-${{ env.RUN_NUMBER }}
    
    - name: Archive Installer
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: ./SysMonitor.Service/SysMonitor.Service/Output/
        retention-days: 5
